<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KUDGUH6" ignored="0" name="企业券-机构司机充值,重复，超额" tests="3" failures="3" timestamp="24 十二月 2018 09:09:06 GMT" time="43.111" errors="0">
  <testcase name="chargeSuccess" time="11.024" classname="com.ui.cases.tvip_qyq.chargeOrangeDriver">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ui.base.Base.getText(Base.java:237)
	at com.ui.cases.tvip_qyq.chargeOrangeDriver.chargeSuccess(chargeOrangeDriver.java:35)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- chargeSuccess -->
  <testcase name="rechargeFail" time="10.027" classname="com.ui.cases.tvip_qyq.chargeOrangeDriver">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ui.base.Base.getText(Base.java:237)
	at com.ui.cases.tvip_qyq.chargeOrangeDriver.rechargeFail(chargeOrangeDriver.java:94)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- rechargeFail -->
  <testcase name="overchargeFail" time="10.022" classname="com.ui.cases.tvip_qyq.chargeOrangeDriver">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.ui.base.Base.getText(Base.java:237)
	at com.ui.cases.tvip_qyq.chargeOrangeDriver.overchargeFail(chargeOrangeDriver.java:149)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- overchargeFail -->
</testsuite> <!-- 企业券-机构司机充值,重复，超额 -->
